### ISSUE TITLE
倒计时结束关服失败

### ISSUE THREAD

**Issue by tanyuguai** [jiajiaxd/VRissues#1]
我用的是控制台发送stop命令的关服方式，1.12.2 cat端，Linux系统面板服。倒计时关服的时候保存完世界然后并没有关服，然后倒计时变成-1，-2，-3.....
下面是报错
[17:49:06] [Craft Scheduler Thread - 1396/WARN] [top.jiajiaxd.www.votereboot.VoteReboot]: [VoteReboot] Plugin VoteReboot vBeta-2.1 generated an exception while executing task 1875623
java.lang.IllegalStateException: Asynchronous player kick!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[AsyncCatcher.class:git-CatServer-1.12.2-fb72736]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.kickPlayer(CraftPlayer.java:262) ~[CraftPlayer.class:git-CatServer-1.12.2-fb72736]
	at top.jiajiaxd.www.votereboot.VoteReboot.reboot(VoteReboot.java:259) ~[?:?]
	at top.jiajiaxd.www.votereboot.VoteReboot$3.run(VoteReboot.java:243) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-fb72736]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-fb72736]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]

**Comment by jiajiaxd** [comment]
可以提供一个更为完整的日记吗

**Comment by tanyuguai** [comment]
[log.txt](https://github.com/jiajiaxd/VRissues/files/4947185/log.txt)

**Comment by jiajiaxd** [comment]
目前发现是踢人功能出现了异常
稍后将更新
更新内容：允许通过配置文件关闭重启前的踢人
